call pathogen#infect()

syntax enable
filetype plugin indent on

set background=dark
colorscheme Tomorrow-Night

set cursorline "highlight cursor line
set noerrorbells " don't make noise
set novisualbell " don't blink
set nostartofline " leave my cursor where it was
set number "line numbers
set numberwidth=4 " We are good up to 99999 lines
set ruler

set autoindent


"search tweaks
set showmatch
set ignorecase

set gdefault "sets /g default on regexes, /g to disable

map <F1> wq

"force 256 color terminal for iterm
let &t_Co=256
