#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
export $TERM=xterm-256color
# Aliases
source ~/.aliases
# Some defalt ENV Variables
source ~/.env_vars
# Handy functions
source ~/.functions
