#!/usr/bin/env bash

find "$HOME/.osx-prime/dotfiles" -type f -exec basename {} \; |
while read dotfile
do
  echo "Force linking Dotfile: $dotfile"
  rm -rf "$HOME/.$dotfile"
  ln -s "$HOME/.osx-prime/dotfiles/$dotfile" "$HOME/.$dotfile"
done

echo "Force linking Bundler config:"
rm -rf  "$HOME/.bundle/config"
ln -s "$HOME/.osx-prime/dotfiles/bundle/config" "$HOME/.bundle/config"
